### ISSUE TITLE
Prometheus setting for custom metrics is outdated

### ISSUE THREAD

**Issue by pavolloffay** [kiali/kiali.io#164]
Is `prometheus_custom_metrics_url` it outdated?  https://www.kiali.io/documentation/runtimes-monitoring/

In my kiali configmap I have:

```
      prometheus:
        auth:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt
          insecure_skip_verify: false
          password: 1X/CET+lKOm0t6R5UfcYdrRMJ1gc6oCbU8DJg/i4IxCHWJ4YrZAW1kRsMvUXGCEh8fYFvjo3QLdzcarJmdqjFtr7IktKRvCnR2hcxgXncibsiKoWcDukilb9qQyw7IlXAc8PWAhy5tRvTN2/tLKAcXFSXxAkifMnEg8QOMFQ504b1Qhi3OaBNTmqBtjYRKQNhetcwTX0l+SKS7zsKISdLig79b4l3lD6zzp9BZeTdAELi7NtceR8nzbGJmRov8LTNwhzr3un20GiUMv4tII5oz9aVKYcqmDWJdY5uPJJf0zBQuZKYI7WhLa1VkVelJ6oU7KQoHxNSYYMFGyouzB9
          token: ''
          type: basic
          use_kiali_token: false
          username: internal
        custom_metrics_url: https://prometheus.istio-system.svc:9090
        url: https://prometheus.istio-system.svc:9090
```
